### ISSUE TITLE
AttributeError: 'SWA' object has no attribute 'defaults'

### ISSUE THREAD

**Issue by bankxi** [mrFahrenhiet/CrackSegmentationDeepLearning#5]
Training Epoch: [1/50] Loss: 0.2198928495248159 Dice: 0.124456192056338 IoU: 0.06566961606343587 Accuracy: 0.13076415409644446 Precision: 0.06728493422269821 Recall: 0.9042726953824362 F1: 0.12471393744150798:   1%|▏                      | 3/340 [00:00<01:46,  3.18it/s]
Traceback (most recent call last):
  File "train.py", line 211, in <module>
    train_logs = train_step(model, optimizer, criteria, trainLoader, accumulation_steps, scaler, epoch, epochs)
  File "train.py", line 52, in train_step
    my_optim.zero_grad()
  File "/home/.conda/envs/lib/python3.7/site-packages/torch/optim/optimizer.py", line 204, in zero_grad
    foreach = self.defaults.get('foreach', False)
AttributeError: 'SWA' object has no attribute 'defaults'

GPU:A5000  torch==1.11.0 torchcontrib==0.0.2

**Comment by bankxi** [comment]
torch==1.10.1 is ok,but torch==1.11.0 in requirements.txt
